const PATH = "data/coins-meta.json";
const state = { cfg: null, meta: null, metaSha: null, currentId: null, pendingFiles: [], removedImageIds: new Set(), busy: false };
const $ = s => document.querySelector(s);
const els = { login:$("#loginScreen"), app:$("#adminApp"), form:$("#coinForm"), empty:$("#emptyEditor"), list:$("#coinList"), search:$("#adminSearch"), status:$("#saveStatus"), connection:$("#connectionState") };
function esc(v="") { return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])); }
function uuid(){ return crypto.randomUUID(); }
function now(){ return new Date().toISOString(); }
function imageUrls(c){ const ids=(c.imageIds||[]).filter(id=>!state.removedImageIds.has(id)); const legacy=ids.map(id=>`https://raw.githubusercontent.com/${state.cfg.owner}/${state.cfg.repo}/${state.cfg.branch}/data/images/${c.id}/${id}.jpg`); return [...legacy,...(c.images||[])]; }
function baseApi(){ return `https://api.github.com/repos/${encodeURIComponent(state.cfg.owner)}/${encodeURIComponent(state.cfg.repo)}`; }
async function api(path, options={}) {
  const response=await fetch(`${baseApi()}${path}`,{...options,headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${state.cfg.token}`,"X-GitHub-Api-Version":"2022-11-28",...(options.headers||{})}});
  if(!response.ok){ const text=await response.text(); const error=new Error(`GitHub ${response.status} — ${text.slice(0,220)}`); error.status=response.status; throw error; }
  return response.status===204?null:response.json();
}
function decode64(s){ const bytes=Uint8Array.from(atob(s.replace(/\n/g,"")),c=>c.charCodeAt(0)); return new TextDecoder().decode(bytes); }
function encode64(s){ const bytes=new TextEncoder().encode(s); let bin=""; for(let i=0;i<bytes.length;i+=0x8000) bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000)); return btoa(bin); }
async function getMetadata(){ const data=await api(`/contents/${PATH}?ref=${encodeURIComponent(state.cfg.branch)}`); state.metaSha=data.sha; state.meta=JSON.parse(decode64(data.content)); state.meta.collections ||= []; state.meta.coins ||= []; }
async function publishMetadata(message){ state.meta.savedAt=now(); const body={message,content:encode64(JSON.stringify(state.meta,null,2)),sha:state.metaSha,branch:state.cfg.branch}; const result=await api(`/contents/${PATH}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); state.metaSha=result.content.sha; }
async function initializeMetadata(){ state.meta={version:2,savedAt:now(),collections:[],geoMap:{},coins:[]}; const body={message:"Initialisation CoinCollector",content:encode64(JSON.stringify(state.meta,null,2)),branch:state.cfg.branch}; const result=await api(`/contents/${PATH}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); state.metaSha=result.content.sha; }
function setBusy(b,text=""){ state.busy=b; els.form.querySelectorAll("button").forEach(x=>x.disabled=b); if(text) setStatus(text); }
function setStatus(text,type=""){ els.status.textContent=text; els.status.className=`save-status ${type}`; }
function collectionName(id){ return state.meta.collections.find(c=>c.id===id)?.name||"Sans collection"; }
function fillCollections(selected=""){ const sel=$("#coinCollection"); sel.innerHTML='<option value="">Sans collection</option>'+state.meta.collections.slice().sort((a,b)=>a.name.localeCompare(b.name,"fr")).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join(""); sel.value=selected||""; }
function renderList(){ const q=els.search.value.toLowerCase().trim(); const coins=state.meta.coins.filter(c=>[c.name,c.location,c.year].join(" ").toLowerCase().includes(q)).sort((a,b)=>String(a.name).localeCompare(String(b.name),"fr")); els.list.innerHTML=coins.map(c=>{const src=imageUrls(c)[0];return `<button class="admin-coin-item ${state.currentId===c.id?'is-active':''}" data-id="${esc(c.id)}">${src?`<img src="${esc(src)}" onerror="this.outerHTML='<span class=admin-coin-thumb>◉</span>'">`:'<span class="admin-coin-thumb">◉</span>'}<span><strong>${esc(c.name||"Sans nom")}</strong><small>${esc(c.year||"")} · ${esc(collectionName(c.collectionId))}</small></span></button>`}).join(""); els.list.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>editCoin(b.dataset.id))); }
function value(id,v=""){ $(id).value=v??""; }
function currentCoin(){ return state.meta.coins.find(c=>c.id===state.currentId); }
function editCoin(id){ state.currentId=id; state.pendingFiles=[]; state.removedImageIds.clear(); const c=currentCoin(); els.empty.hidden=true; els.form.hidden=false; $("#editorTitle").textContent=c.name||"Modifier la pièce"; $("#editorKicker").textContent="Modifier la fiche"; value("#coinId",c.id); value("#coinName",c.name); value("#coinYear",c.year); fillCollections(c.collectionId); value("#coinLocation",c.location); value("#coinCountry",c.country); value("#coinDenomination",c.denomination); value("#coinMetal",c.metal); value("#coinCondition",c.condition); value("#coinMint",c.mint); value("#coinQuantity",c.quantity||1); value("#coinEstimatedValue",c.estimatedValue); value("#coinAcquisitionDate",c.acquisitionDate); value("#coinTags",(c.tags||[]).join(", ")); value("#coinNotes",c.notes); $("#deleteCoinButton").hidden=false; renderImages(); renderList(); setStatus(""); }
function newCoin(){ state.currentId=null; state.pendingFiles=[]; state.removedImageIds.clear(); els.empty.hidden=true; els.form.hidden=false; els.form.reset(); value("#coinId",uuid()); fillCollections(""); value("#coinQuantity",1); $("#editorTitle").textContent="Nouvelle pièce"; $("#editorKicker").textContent="Créer une fiche"; $("#deleteCoinButton").hidden=true; renderImages(); renderList(); setStatus(""); }
function renderImages(){ const c=currentCoin()||{id:$("#coinId").value,imageIds:[],images:[]}; const existing=imageUrls(c).map((src,i)=>({src,type:"existing",id:(c.imageIds||[])[i]||null})); const pending=state.pendingFiles.map((p,i)=>({src:p.preview,type:"pending",index:i})); $("#imagePreview").innerHTML=[...existing,...pending].map(item=>`<div class="admin-image"><img src="${esc(item.src)}"><button type="button" data-type="${item.type}" data-id="${esc(item.id||"")}" data-index="${item.index??""}">×</button>${item.type==='pending'?'<span class="pending-badge">À publier</span>':''}</div>`).join(""); $("#imagePreview").querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{ if(b.dataset.type==="pending"){ URL.revokeObjectURL(state.pendingFiles[Number(b.dataset.index)].preview); state.pendingFiles.splice(Number(b.dataset.index),1); } else if(b.dataset.id){ state.removedImageIds.add(b.dataset.id); } renderImages(); })); }
async function compress(file){ const bitmap=await createImageBitmap(file); const max=1500, scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)); const canvas=document.createElement("canvas"); canvas.width=Math.round(bitmap.width*scale); canvas.height=Math.round(bitmap.height*scale); canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height); return new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error("Compression impossible")),"image/jpeg",.84)); }
async function blob64(blob){ const buffer=new Uint8Array(await blob.arrayBuffer()); let bin=""; for(let i=0;i<buffer.length;i+=0x8000) bin+=String.fromCharCode(...buffer.subarray(i,i+0x8000)); return btoa(bin); }
async function uploadImage(coinId,pending,index,total){ setStatus(`Publication de la photo ${index}/${total}…`); const imgId=uuid(); const blob=await compress(pending.file); await api(`/contents/data/images/${coinId}/${imgId}.jpg`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:`Ajout photo ${coinId}`,content:await blob64(blob),branch:state.cfg.branch})}); return imgId; }
function formCoin(){ const existing=currentCoin(); return {...(existing||{}),id:$("#coinId").value||uuid(),name:$("#coinName").value.trim(),year:Number($("#coinYear").value),collectionId:$("#coinCollection").value||null,location:$("#coinLocation").value.trim(),country:$("#coinCountry").value.trim(),denomination:$("#coinDenomination").value.trim(),metal:$("#coinMetal").value.trim(),condition:$("#coinCondition").value.trim(),mint:$("#coinMint").value.trim(),quantity:Number($("#coinQuantity").value)||1,estimatedValue:$("#coinEstimatedValue").value?Number($("#coinEstimatedValue").value):null,acquisitionDate:$("#coinAcquisitionDate").value||"",tags:$("#coinTags").value.split(",").map(x=>x.trim()).filter(Boolean),notes:$("#coinNotes").value.trim(),createdAt:existing?.createdAt||now(),updatedAt:now(),imageIds:(existing?.imageIds||[]).filter(id=>!state.removedImageIds.has(id))}; }
async function saveCoin(e){ e.preventDefault(); if(state.busy)return; const coin=formCoin(); if(!coin.name||!coin.year)return setStatus("Le nom et l’année sont obligatoires.","error"); try{setBusy(true,"Préparation…"); for(let i=0;i<state.pendingFiles.length;i++) coin.imageIds.push(await uploadImage(coin.id,state.pendingFiles[i],i+1,state.pendingFiles.length)); const idx=state.meta.coins.findIndex(c=>c.id===coin.id); if(idx>=0)state.meta.coins[idx]=coin;else state.meta.coins.push(coin); await publishMetadata(`${idx>=0?"Mise à jour":"Ajout"} : ${coin.name}`); state.currentId=coin.id; state.pendingFiles.forEach(p=>URL.revokeObjectURL(p.preview)); state.pendingFiles=[]; state.removedImageIds.clear(); renderList(); editCoin(coin.id); setStatus("La pièce a été publiée avec succès.","success"); }catch(err){setStatus(err.status===409?"Conflit de modification : recharge l’administration puis recommence.":err.message,"error");}finally{setBusy(false);}}
async function deleteCoin(){ const c=currentCoin(); if(!c||!confirm(`Supprimer « ${c.name} » de la collection ?`))return; try{setBusy(true,"Suppression…"); state.meta.coins=state.meta.coins.filter(x=>x.id!==c.id); await publishMetadata(`Suppression : ${c.name}`); state.currentId=null; els.form.hidden=true; els.empty.hidden=false; renderList();}catch(err){setStatus(err.message,"error");}finally{setBusy(false);}}
function renderCollections(){ $("#collectionsList").innerHTML=state.meta.collections.slice().sort((a,b)=>a.name.localeCompare(b.name,"fr")).map(c=>`<div class="collection-row" data-id="${esc(c.id)}"><input class="admin-input" value="${esc(c.name)}"><button class="button save-col">Renommer</button><button class="button danger del-col">Supprimer</button></div>`).join(""); $("#collectionsList").querySelectorAll(".collection-row").forEach(row=>{ row.querySelector(".save-col").onclick=async()=>{const c=state.meta.collections.find(x=>x.id===row.dataset.id);c.name=row.querySelector("input").value.trim();await publishMetadata(`Renommage collection : ${c.name}`);renderCollections();renderList();fillCollections(currentCoin()?.collectionId);}; row.querySelector(".del-col").onclick=async()=>{const c=state.meta.collections.find(x=>x.id===row.dataset.id);if(!confirm(`Supprimer la collection « ${c.name} » ? Les pièces seront placées sans collection.`))return;state.meta.coins.forEach(x=>{if(x.collectionId===c.id)x.collectionId=null;});state.meta.collections=state.meta.collections.filter(x=>x.id!==c.id);await publishMetadata(`Suppression collection : ${c.name}`);renderCollections();renderList();fillCollections(currentCoin()?.collectionId);}; }); }
async function addCollection(){ const input=$("#newCollectionName"),name=input.value.trim();if(!name)return;state.meta.collections.push({id:uuid(),name,createdAt:now()});await publishMetadata(`Ajout collection : ${name}`);input.value="";renderCollections();fillCollections(currentCoin()?.collectionId);renderList();}
async function login(e){ e.preventDefault(); const error=$("#loginError");error.textContent="";state.cfg={owner:$("#ownerInput").value.trim(),repo:$("#repoInput").value.trim(),branch:$("#branchInput").value.trim(),token:$("#tokenInput").value.trim()};try{await getMetadata();}catch(err){if(err.status===404&&confirm("Le fichier de données n’existe pas. Créer une collection vide ?")){await initializeMetadata();}else{error.textContent=err.message;return;}}sessionStorage.setItem("coincollector-admin",JSON.stringify(state.cfg));openApp();}
function openApp(){els.login.hidden=true;els.app.hidden=false;$("#logoutButton").hidden=false;els.connection.textContent=`${state.cfg.owner}/${state.cfg.repo} · ${state.cfg.branch}`;fillCollections();renderList();}
function logout(){sessionStorage.removeItem("coincollector-admin");location.reload();}
$("#loginForm").addEventListener("submit",login);$("#coinForm").addEventListener("submit",saveCoin);$("#newCoinButton").onclick=newCoin;$("#deleteCoinButton").onclick=deleteCoin;$("#logoutButton").onclick=logout;els.search.addEventListener("input",renderList);$("#collectionsButton").onclick=()=>{renderCollections();$("#collectionsDialog").showModal();};$("#addCollectionButton").onclick=addCollection;$("#photoInput").addEventListener("change",e=>{[...e.target.files].forEach(file=>state.pendingFiles.push({file,preview:URL.createObjectURL(file)}));e.target.value="";renderImages();});
(async()=>{const saved=sessionStorage.getItem("coincollector-admin");if(!saved)return;try{state.cfg=JSON.parse(saved);await getMetadata();openApp();}catch(_){sessionStorage.removeItem("coincollector-admin");}})();
